---
title: "dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup }
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------
```{r}
data("ny_noaa")

ny_noaa = 
  ny_noaa %>% 
  as_tibble(ny_noaa) %>% 
  separate(date, into = c("year", "month", "day"), sep = "-", convert = TRUE)


```

### Chart A: 

```{r}

 ny_noaa %>% 
  arrange(desc(snow)) %>% 
  filter(snow > 1104) %>% 
  select(year, snow) %>% 
   mutate(
     year = as.factor(year),
     year = fct_reorder(year, snow)
   ) %>% 
   plot_ly(
     x = ~ year, y = ~snow,
     type = "bar",
     colors = "viridis"
   ) %>% 
   layout(
     title = "Top 5 years with Heaviest Snowfall (mm)",
     xaxis = list(title = "Year"),
     yaxis = list(title = "Snowfall (mm)")
   )



```

Column {data-width=350}
-----------------------------------------------------------------------
```{r}
ny_noaa_2 = 
  ny_noaa %>% 
  as_tibble(ny_noaa) %>% 
    janitor::clean_names() %>% 
  mutate(
   tmax = as.integer(tmax),
    tmin = as.integer(tmin),
    prcp = prcp/10,
    tmax = tmax/10,
    tmin = tmin/10,
  ) %>% mutate(
    text_label = str_c("ID: ", id)
  ) %>% 
  sample_n(1000) %>% 
  drop_na(prcp)
```

### Chart B

```{r}

ny_noaa_2 %>% 
  plot_ly(
    x = ~ tmin, y = ~ tmax,
    type = "scatter", mode = "markers",
    alpha = .5,
    colors = "viridis",
    text = ~ text_label,
    color = ~id,
    showlegend = FALSE
  ) %>% 
  layout(
    title = "Tmax vs Tmin",
    xaxis = list(title = "Tmin"),
    yaxis = list(title = "Tmax")
  )


```

### Chart C

```{r}

ny_noaa_2 %>% 
  mutate(
    prcp = as.integer(prcp),
    prcp = prcp/10,
    year = as.factor(year)
  ) %>% 
  plot_ly(
    y = ~prcp,
    color = ~year,
    type = "box",
    colors = "viridis"
  ) %>% 
  layout(
    title = "Precipitation Per Year",
    xaxis = list(title = "Year"),
    yaxis = list(title = "Precipitation")
  )

```

